

import '../cores/cores.dart';

final categoriesJSON = [
  {
    "id": 1,
    "name": "Courses",
    "slug": "courses",
    "imagePath": Assets.iconsSVG.pencil,
  },
  {
    "id": 2,
    "name": "GK & Quiz",
    "slug": "gk",
    "imagePath": Assets.iconsSVG.bookSchool,
  },
  {
    "id": 3,
    "name": "Notice",
    "slug": "notice",
    "imagePath": Assets.iconsSVG.microphone,
  },
  {
    "id": 4,
    "name": "Exam",
    "slug": "exam",
    "imagePath": Assets.iconsSVG.graduate,
  },

  // Subjects
  {"id": 5, "name": "Bangla", "slug": "bangla", "imagePath": ""},
  {"id": 6, "name": "English", "slug": "english", "imagePath": ""},
  {"id": 7, "name": "Mathematics", "slug": "math", "imagePath": ""},
  {"id": 8, "name": "Science", "slug": "science", "imagePath": ""},
  {"id": 9, "name": "Biology", "slug": "biology", "imagePath": ""},
  {"id": 10, "name": "Chemistry", "slug": "chemistry", "imagePath": ""},
  {"id": 11, "name": "Physics", "slug": "physics", "imagePath": ""},
  {"id": 12, "name": "ICT", "slug": "ict", "imagePath": ""},
  {"id": 13, "name": "Islamic Studies", "slug": "islamic", "imagePath": ""},
  {"id": 14, "name": "Religion", "slug": "religion", "imagePath": ""},
  {"id": 15, "name": "Geography", "slug": "geography", "imagePath": ""},
  {"id": 16, "name": "Civics", "slug": "civics", "imagePath": ""},
  {"id": 17, "name": "Economics", "slug": "economics", "imagePath": ""},
  {"id": 18, "name": "Agriculture", "slug": "agriculture", "imagePath": ""},
  {"id": 19, "name": "General Knowledge", "slug": "gk", "imagePath": ""},
  {"id": 20, "name": "Physical Education", "slug": "physical", "imagePath": ""},

  // Classes
  {"id": 21, "name": "Class 1", "slug": "class-1", "imagePath": ""},
  {"id": 22, "name": "Class 2", "slug": "class-2", "imagePath": ""},
  {"id": 23, "name": "Class 3", "slug": "class-3", "imagePath": ""},
  {"id": 24, "name": "Class 4", "slug": "class-4", "imagePath": ""},
  {"id": 25, "name": "Class 5", "slug": "class-5", "imagePath": ""},
  {"id": 26, "name": "Class 6", "slug": "class-6", "imagePath": ""},
  {"id": 27, "name": "Class 7", "slug": "class-7", "imagePath": ""},
  {"id": 28, "name": "Class 8", "slug": "class-8", "imagePath": ""},
  {"id": 29, "name": "Class 9", "slug": "class-9", "imagePath": ""},

  // Secondary & Higher Secondary
  {"id": 30, "name": "SSC", "slug": "ssc", "imagePath": ""},
  {"id": 31, "name": "HSC", "slug": "hsc", "imagePath": ""},
  {"id": 32, "name": "HSC Science", "slug": "hsc-science", "imagePath": ""},
  {"id": 33, "name": "HSC Humanities", "slug": "hsc-humanities", "imagePath": ""},
  {"id": 34, "name": "HSC Business Studies", "slug": "hsc-business", "imagePath": ""},

  // University/College Streams
  {"id": 35, "name": "Computer Science (CSE)", "slug": "cse", "imagePath": ""},
  {"id": 36, "name": "Business Administration (BBA)", "slug": "bba", "imagePath": ""},
  {"id": 37, "name": "Electrical & Electronic Engineering (EEE)", "slug": "eee", "imagePath": ""},
  {"id": 38, "name": "Mechanical Engineering", "slug": "me", "imagePath": ""},
  {"id": 39, "name": "Civil Engineering", "slug": "civil", "imagePath": ""},
  {"id": 40, "name": "Law", "slug": "law", "imagePath": ""},
  {"id": 41, "name": "Journalism", "slug": "journalism", "imagePath": ""},
  {"id": 42, "name": "Sociology", "slug": "sociology", "imagePath": ""},
  {"id": 43, "name": "Anthropology", "slug": "anthropology", "imagePath": ""},
  {"id": 44, "name": "Philosophy", "slug": "philosophy", "imagePath": ""},
  {"id": 45, "name": "History", "slug": "history", "imagePath": ""},

  // Skills
  {"id": 46, "name": "Public Speaking", "slug": "public-speaking", "imagePath": ""},
  {"id": 47, "name": "Debate", "slug": "debate", "imagePath": ""},
  {"id": 48, "name": "Creative Writing", "slug": "creative-writing", "imagePath": ""},
  {"id": 49, "name": "Critical Thinking", "slug": "critical-thinking", "imagePath": ""},
  {"id": 50, "name": "Programming", "slug": "programming", "imagePath": ""},
  {"id": 51, "name": "Web Development", "slug": "web-dev", "imagePath": ""},
  {"id": 52, "name": "Mobile App Development", "slug": "mobile-dev", "imagePath": ""},
  {"id": 53, "name": "AI & Machine Learning", "slug": "ai", "imagePath": ""},
  {"id": 54, "name": "Graphic Design", "slug": "graphic-design", "imagePath": ""},
  {"id": 55, "name": "Video Editing", "slug": "video-editing", "imagePath": ""},

  // Language Learning
  {"id": 56, "name": "Spoken English", "slug": "spoken-english", "imagePath": ""},
  {"id": 57, "name": "IELTS", "slug": "ielts", "imagePath": ""},
  {"id": 58, "name": "TOEFL", "slug": "toefl", "imagePath": ""},
  {"id": 59, "name": "Arabic", "slug": "arabic", "imagePath": ""},
  {"id": 60, "name": "Chinese", "slug": "chinese", "imagePath": ""},

  // Additional categories (61+)
  {"id": 61, "name": "Accounting", "slug": "accounting", "imagePath": ""},
  {"id": 62, "name": "Marketing", "slug": "marketing", "imagePath": ""},
  {"id": 63, "name": "Finance", "slug": "finance", "imagePath": ""},
  {"id": 64, "name": "Banking", "slug": "banking", "imagePath": ""},
  {"id": 65, "name": "Tourism & Hospitality", "slug": "tourism", "imagePath": ""},
  {"id": 66, "name": "Textile Engineering", "slug": "textile", "imagePath": ""},
  {"id": 67, "name": "Architecture", "slug": "architecture", "imagePath": ""},
  {"id": 68, "name": "Microbiology", "slug": "microbiology", "imagePath": ""},
  {"id": 69, "name": "Environmental Science", "slug": "environmental-science", "imagePath": ""},
  {"id": 70, "name": "Nutrition & Food Science", "slug": "nutrition", "imagePath": ""},
  {"id": 71, "name": "Psychology", "slug": "psychology", "imagePath": ""},
  {"id": 72, "name": "Fine Arts", "slug": "fine-arts", "imagePath": ""},
  {"id": 73, "name": "Music", "slug": "music", "imagePath": ""},
  {"id": 74, "name": "Performing Arts", "slug": "performing-arts", "imagePath": ""},
  {"id": 75, "name": "Film & Media", "slug": "film-media", "imagePath": ""},
  {"id": 76, "name": "Journalism & Mass Comm", "slug": "mass-comm", "imagePath": ""},
  {"id": 77, "name": "Law Entrance Prep", "slug": "law-prep", "imagePath": ""},
  {"id": 78, "name": "Medical Entrance Prep", "slug": "medical-prep", "imagePath": ""},
  {"id": 79, "name": "PSC Exam Prep", "slug": "psc-prep", "imagePath": ""},
  {"id": 80, "name": "Vocational Skills", "slug": "vocational-skills", "imagePath": ""},
  {"id": 81, "name": "Tailoring & Dress Making", "slug": "tailoring", "imagePath": ""},
  {"id": 82, "name": "Driving & Transport", "slug": "driving", "imagePath": ""},
  {"id": 83, "name": "Cooking & Bakery", "slug": "cooking", "imagePath": ""},
  {"id": 84, "name": "Beauty & Cosmetology", "slug": "beauty", "imagePath": ""},
  {"id": 85, "name": "Web Design", "slug": "web-design", "imagePath": ""},
  {"id": 86, "name": "SEO & Digital Marketing", "slug": "seo-marketing", "imagePath": ""},
  {"id": 87, "name": "Mobile Repair", "slug": "mobile-repair", "imagePath": ""},
  {"id": 88, "name": "Electrical Repair", "slug": "electrical-repair", "imagePath": ""},
  {"id": 89, "name": "Plumbing", "slug": "plumbing", "imagePath": ""},
  {"id": 90, "name": "Graphic Animation", "slug": "animation", "imagePath": ""},
  {"id": 91, "name": "Photography", "slug": "photography", "imagePath": ""},
  {"id": 92, "name": "Public Health", "slug": "public-health", "imagePath": ""},
  {"id": 93, "name": "Healthcare Assistant", "slug": "healthcare-assistant", "imagePath": ""},
  {"id": 94, "name": "Pharmacy Technician", "slug": "pharmacy-tech", "imagePath": ""},
  {"id": 95, "name": "Graphic UI/UX", "slug": "ui-ux", "imagePath": ""},
  {"id": 96, "name": "Robotics", "slug": "robotics", "imagePath": ""},
  {"id": 97, "name": "Blockchain & Crypto", "slug": "blockchain", "imagePath": ""},
  {"id": 98, "name": "Data Science", "slug": "data-science", "imagePath": ""},
  {"id": 99, "name": "Cyber Security", "slug": "cyber-security", "imagePath": ""},
  {"id": 100, "name": "Foreign Languages", "slug": "foreign-langs", "imagePath": ""},
];
